global:
  scrape_interval:     15s
  scrape_timeout:      10s
  evaluation_interval: 15s
  external_labels:
    monitor: 'Alertmanager'

scrape_configs:

  - job_name: 'prometheus_metrics'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'page_load'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets: ['https://google.com', 'https://www.microsoft.com', 'https://aws.amazon.com', 'https://bbc.co.uk']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [__address__]
        regex: 'https?://(.*)'
        replacement: $1
        target_label: host
      - target_label: __address__
        replacement: blackbox:9115 

  - job_name: 'ping'
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets: ['google.com', 'www.microsoft.com', 'aws.amazon.com', 'bbc.co.uk', '100.65.8.1', '192.168.1.1']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  - job_name: 'dns_lookup'
    metrics_path: /probe
    params:
      module: [dns]
    static_configs:
      - targets: ['8.8.8.8', '1.1.1.1', '185.165.194.4']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
    