{
 "title": "Internet Connectivity",
 "description": "Illustration of internet connectivity",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Probe Failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(probe_success == bool 0)", "legendFormat": "failures" }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "timeseries",
   "description": "The time taken to load web pages",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(host) (probe_http_duration_seconds)",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Ping Duration",
   "type": "timeseries",
   "description": "The time taken to ping the host",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(instance) (probe_icmp_duration_seconds)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "DNS Duration",
   "type": "timeseries",
   "description": "The time taken to perform a DNS lookup for the domain ui.com",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(instance) (probe_dns_duration_seconds)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}